# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170623_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
